### ISSUE TITLE
Multimedia in antox

### ISSUE THREAD

**Issue by SergeyDjam** [Antox/Antox#246]
A/V in Antox is?  I not find this In program preference

**Comment by wiiaam** [comment]
Currently Antox does not support A/V although work on this is being made on the [audio branch](https://github.com/Antox/Antox/tree/audio). Current progress for A/V can be tracked with issue https://github.com/Antox/Antox/issues/104

Builds for this can be found [here](https://build.tox.chat/job/antox-audio_build_android_arm64_release/). Note that this currently has many bugs and is not recommended for daily usage.

If you wish to try this, remember to export your Tox profile before installing as you will need to uninstall the old application (due to the version number being lower). Please do not open any issues about any bugs found in this build.
