### ISSUE TITLE
failed to load required library, cannot create non-incognito profile

### ISSUE THREAD

**Issue by kotoroshinoto** [Antox/Antox#252]
as in the title. I don't really know where to go from here.

**Comment by wiiaam** [comment]
Fixed in 0.23.337
Check for an update in the next few days

**Comment by subliun** [comment]
>few days

**Comment by kotoroshinoto** [comment]
secondary question, is it possible to use a profile I created on the PC through qTox?

**Comment by kotoroshinoto** [comment]
nvm I figured out how to do the export/import

**Comment by sledgehammer999** [comment]
The problem persists with 0.23.337 (and android 4.0.3)

**Comment by sledgehammer999** [comment]
This error still happens with 0.23.354

**Comment by wiiaam** [comment]
@sledgehammer999 what device are you using?

**Comment by sledgehammer999** [comment]
@wiiaam it is a chinese phone. It is called "Zopo zp500". It has an MTK MT6575 CPU. And android 4.0.3.
However, I am waiting my "Xiaomi redmi 3" phone, which android 5.1 soon. So I'll be able to test on a much more recent android.

**Comment by wiiaam** [comment]
@sledgehammer999 It should be working fine with that cpu as it is an arm-v7 which is supported by the native libraries. If you were able to connect your phone to adb and find a stack trace I could try and solve the problem

**Comment by sledgehammer999** [comment]
>If you were able to connect your phone to adb and find a stack trace I could try and solve the problem

Can you give me instructions? I know my way around the cmd line. I just want you to give me the commands.

**Comment by wiiaam** [comment]
The easiest way to do this is to just install android studio and use the built in tools to view the logcat. Otherwise,

For windows you will need the android sdk http://developer.android.com/sdk/index.html#Other

Install that, run the sdk manager then install the platform tools. This will install adb

For debian based linux you can install `apt-get install android-tools-adb`, which will provide the adb binary.

Once you have connected your device to adb you can use `adb logcat` to view the logs. More info on adb logcat can be found here http://developer.android.com/tools/help/logcat.html

**Comment by sledgehammer999** [comment]
Can I access the logs from the device if I have root? If yes, tell me where to look?

**Comment by sledgehammer999** [comment]
I managed to copy the logcat output from my phone using root. Here is an excerpt from it. I hope I didn't miss something. (I think in between are some irrelevant things): http://pastebin.com/ctQ2xhP5
