### ISSUE TITLE
Tox Nodes are not using TCP 443.

### ISSUE THREAD

**Issue by gqmrtgma** [Antox/Antox#279]
connecting to TCP 672 194.249.212.109:h
connecting to TCP 808 178.62.250.138:33
connecting to TCP 860 78.225.128.39:334
connecting to TCP 960 192.210.149.121:3
connecting to TCP 940 195.154.119.113:3
connecting to TCP 1004 205.185.116.116:
connecting to TCP 1104 104.167.101.29:3
connecting to TCP 1184 23.226.230.47:334
connecting to TCP 1156 76.191.23.96:334
connecting to TCP 1204 103.38.216.87:33
connecting to TCP 1220 192.254.75.102:3
connecting to TCP 640 46.38.239.179:334
connecting to TCP 1216 130.133.110.14:3
connecting to TCP 656 212.71.252.109:33
connecting to TCP 604 192.99.168.140:33
connecting to TCP 712 108.61.165.198:3
connecting to TCP 752 178.21.112.187:3
connecting to TCP 728 195.154.109.148:
connecting to TCP 780 80.232.246.79:33
connecting to TCP 724 198.98.51.198:33
connecting to TCP 704 144.76.60.215:33
connecting to TCP 692 192.3.173.88:3344

Why Tox's nodes are not 443? Filtered network are not allowing abnormal ports.
How about using 443 TCP, like most of Tor nodes offer?

**Comment by wiiaam** [comment]
Because there are a wide array of ports to use. Tor uses port 443 as that is the standard https port. Tox by default uses 33445, and using 443 instead would disallow people to run a web server on their server. Though, it is entirely the decision of the node owner to choose which port their node listens on.
<br>

>abnormal ports

What do you mean by this? 80 and 443 (http/https) are the most common ports used but most applications will have their own port number if they connect to a server. A common list of ports can be found at https://en.wikipedia.org/wiki/List_of_TCP_and_UDP_port_numbers
