### ISSUE TITLE
FDroid: "Error getting index file"

### ISSUE THREAD

**Issue by rugk** [Antox/Antox#283]
The [FDroid repo](https://pkg.tox.chat/fdroid/repo/) always shows  an error: `Error getting index file`

**Comment by wiiaam** [comment]
Make sure that the repo you are adding is the correct address. I just tested it and it is working fine for me on two different devices. You can even see that the index file is there when you navigate to the repo link.

`https://pkg.tox.chat/fdroid/repo/`

The `/fdroid/repo/` part is important, make sure this is correct.

**Comment by rugk** [comment]
Yeah, I just noticed there was another issue (from another repo) causing this. Sad I cannot see which repo exactly causes such issues.

**Comment by dienteperro** [comment]
In my case the problem was caused by my local wifi router set to “AP Isolation”. This setting in the wifi router prevents wifi clients connect between them. After disable the setting in the router the repos downloaded fine. Later after activate the setting again f-droid app was unable to download repos. Tried to download the repo file in Chrome mobile and it warned about the SSL certificate being redirected or similar error.

**Comment by codegen284** [comment]
Disabed adblock before update may solve the problem.
