### ISSUE TITLE
Remove :-)(emoji) button from virtual keyboard.

### ISSUE THREAD

**Issue by ghost** [Antox/Antox#287]
1. Tap "Send a message"
2. Keyboard will appear, but "Enter" key was replaced to emoji button
which irritates me. Why do I have to tap ">" button to send a message instead of plain-good
Enter key?

So.

Please consider adding an option to disable emoji button.

**Comment by ghostlands** [comment]
I also absolutely hate this key, but for a different reason: in my app, the key obscured by the smiley is a return key, not a send key. The former is the only way to create breaks/paragraphs.

Wall of text messages are crap and this stupid smiley is _always in the way_ of making my messages readable. Please remove it!

Alternatively, the current scheme could be reversed, so that the return key is the default one visible, and the smiley is accessible via the number layout.

As for `return-vs-enter/send`, I'll leave that argument for another place and time. At the very least, please remove the smiley or tuck it away somewhere less obtrusive.

**Comment by ghostlands** [comment]
I also absolutely hate this key, but for a different reason: in my app, the key obscured by the smiley is a return key, not a send key. The former is the only way to create breaks/paragraphs.

Wall of text messages are crap and this stupid smiley is _always in the way_ of making my messages readable. Please remove it!

Alternatively, the current scheme could be reversed, so that the return key is the default one visible, and the smiley is accessible via the number layout.

As for `return-vs-enter/send`, I'll leave that argument for another place and time. At the very least, please remove the smiley or tuck it away somewhere less obtrusive.

**Comment by ghostlands** [comment]
I also absolutely hate this key, but for a different reason: in my app, the key obscured by the smiley is a return key, not a send key. The former is the only way to create breaks/paragraphs.

Wall of text messages are crap and this stupid smiley is _always in the way_ of making my messages readable. Please remove it!

Alternatively, the current scheme could be reversed, so that the return key is the default one visible, and the smiley is only accessible via the number layout or the extra symbols layout.

As for `return-vs-enter/send`, I'll leave that argument for another place and time. At the very least, please remove the smiley or tuck it away somewhere less obtrusive. Ideally the key will become obsolete anyway if stickers become available.

Also, some people don't like noses on their smileys. Just saying.

**Comment by wiiaam** [comment]
I like to share my current emotion with emojis and i believe that having an emoji button is much more important than a send button. Removing the emoji button would stop people sending :eggplant:s with would probably anger @installgen2

**Comment by installgen2** [comment]
@wiiaam but unless your phone is shit you can still access emoji from your keyboard easily

**Comment by ghostlands** [comment]
@wiiaam But is it more important than a newline/return button?

Also, that particular emojii key is only useful for conveying one emotion anyway, which is a whole other weird thing by itself. I personally harbor a range of emotions that I prefer to convey. Maybe there could be a whole other key mapping for emojii. Or maybe there needs to be a button added to the left or right side of the text input area exclusively for emojii/stickers (I don't know the difference).

**Comment by ghostlands** [comment]
@wiiaam But is it more important than a newline/return button? Also, that particular emojii key is only useful for conveying one emotion anyway, which is a whole other weird thing by itself. I personally harbor a range of emotions that I prefer to convey. Maybe there could be a whole other key mapping for emojii. Or maybe there needs to be a button added to the left or right side of the text input area exclusively for emojii/stickers (I don't know the difference). Maybe I should write all of my bug reports/requests without paragraphs for awhile to help make the point. ;)

**Comment by qasmoke** [comment]
> having an emoji button is much more important than a send button

Care to explain more about this?

**Comment by wiiaam** [comment]
Well the modern design for messaging applications is the send button is next to the input box, and the emoji key takes place on the keyboard. As for having an enter button, this is an instant messaging application, Line breaks are for emails (and github comments).

I personally like to sign my messages off with a good old :ok_hand::ok_hand::100::joy::joy: so having instant access to the emoji button has proven useful time and time again. I do understand however that some people might not share my enthusiasm with emojis, so I will try to add an option to choose what one shows up on your keyboard

**Comment by ghostlands** [comment]
> this is an instant messaging application, Line breaks are for emails (and github comments)

Discouraging line breaks is not a spec or any other kind of industry standard for IM that I know of. Tox has no problem with them and discouraging them would be an artificial restriction.

As a side note, distinctions from the user perspective between different types of messaging are becoming arbitrary, especially so on smartphones. Increasingly the only truly consistent user experience differences between IM and email  are the visible metadata, the subject/to/from fields. The remainder of differences are traditional stylistic trends in the GUI.

An example of what I'm talking about: http://quickmsg.vreeken.net

**Comment by wiiaam** [comment]
I'm not discouraging line breaks, but it doesn't mean they are necessary. Most instant messaging applications replace the enter key on their keyboards with the emoji key, and web applications use enter to send and shift-enter to create line breaks (if that's even supported, lots of applications filter line breaks).

I probably use a line break in an instant message about once a week, because its not useful. I'm not sending someone a report, I'm asking if they want to hang out on Saturday. Also if people feel the need to send multiple lines in a message, most people would just go ahead and send two messages.

**Comment by wiiaam** [comment]
Note that you can also access the return button when the emoji button is enabled by pressing shift.
