### ISSUE TITLE
Add to official F-Droid Repo

### ISSUE THREAD

**Issue by Nutomic** [Antox/Antox#341]
Seeing as Antox is available on Google Play, you should also put it into the official F-Droid repo. I know that its possible to install from your repo, but that's much more effort for users.

**Comment by wiiaam** [comment]
The problem with this is that apps on the official F-Droid repo are not signed by the developer, meaning that F-Droid is able to modify the application and distribute it if they so wished. Because they are not signed by us, there will be no way of telling whether or not the app has been tampered with.

**Comment by licaon-kter** [comment]
Reproducible builds will fix that.

**Comment by zoff99** [comment]
thats not the problem, f-droid do not allow all maven repos.
also they don't allow *.so *.jar files, all must be compiled from source.

if you can help, that would be good.

**Comment by wiiaam** [comment]
Maybe one day when tox is in release
